driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-19
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ul-nginx::default]
  - name: source
    run_list:
      - recipe[ul-nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[ul-nginx::repo]
      - recipe[ul-nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[ul-nginx::source]
    attributes:
      nginx:
        source:
          modules:
            - ul-nginx::headers_more_module
            - ul-nginx::http_auth_request_module
            - ul-nginx::http_echo_module
            - ul-nginx::http_geoip_module
            - ul-nginx::http_gzip_static_module
            - ul-nginx::http_realip_module
            - ul-nginx::http_spdy_module
            - ul-nginx::http_ssl_module
            - ul-nginx::http_stub_status_module
            - ul-nginx::naxsi_module
            - ul-nginx::ngx_devel_module
            - ul-nginx::ngx_lua_module
            - ul-nginx::openssl_source
            - ul-nginx::upload_progress_module
